version: "3"

services:
  telbot:
    build: .
    container_name: rss-summarizer-tel-bot-python
    restart: unless-stopped
    environment:
      - TELEGRAM_PROXY=
      - TELEGRAM_TOKEN=
      - COMMA_FEED_API_URL=http://commafeed:8082/rest/
    volumes:
      - ./configs:/configs

  commafeed:
    image: athou/commafeed:latest
    restart: unless-stopped
    environment:
      - CF_DATABASE_DRIVERCLASS=org.postgresql.Driver
      - CF_DATABASE_URL=jdbc:postgresql://postgresql:5432/commafeed
      - CF_DATABASE_USER=commafeed
      - CF_DATABASE_PASSWORD=commafeed
      - CF_APP_ALLOWREGISTRATIONS=true
    volumes:
      - ./data:/commafeed/data
    ports:
      - 8082:8082

  postgresql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: commafeed
      POSTGRES_DB: commafeed
    volumes:
      - ./db:/var/lib/postgresql/data
